// <auto-generated />
namespace TeduShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_Table_Identity_20200405 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Table_Identity_20200405));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051609118_add_Table_Identity_2020.04.05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
