// <auto-generated />
namespace TeduShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_Init_20200403 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Init_20200403));
        
        string IMigrationMetadata.Id
        {
            get { return "202004031516108_add_Init_2020.04.03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
